baseurl = "http://pankona.github.io/"
title = "make clean; make"
author = "pankona"
languageCode = "en-us"

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[Params]
  hideshareoptions = true
  twitter = "gohan_pan_gohan"
  github  = "pankona"
